# Generated by scripts/generate-command-completions.py from Fabric CommandSpec.
# command-spec-sha256: 940a8a40b696909a23cb30d2efb4642b9164700e15abc2f859cbb5a6e83869ec

_aletheon_cli_completion() {
    local cur prev command_path i
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]:-}

    case "$prev" in
        -C|--working-dir|--add-dir|--config|-c|--env|--project-dir|-d)
            COMPREPLY=($(compgen -d -- "$cur")); return ;;
        path)
            COMPREPLY=($(compgen -f -- "$cur")); return ;;
        -P|--permission-mode)
            COMPREPLY=($(compgen -W "safe dev full" -- "$cur")); return ;;
        --output)
            COMPREPLY=($(compgen -W "text json jsonl" -- "$cur")); return ;;
        --sandbox)
            COMPREPLY=($(compgen -W "auto require forbid" -- "$cur")); return ;;
    esac

    if ((COMP_CWORD == 1)); then
        COMPREPLY=($(compgen -W "completion config daemon doctor exec extension memory resume review run version --help --version --full --permission-mode --message --socket --task-kind -C --add-dir" -- "$cur"))
        return
    fi

    command_path=""
    for ((i=1; i<COMP_CWORD; i++)); do
        command_path=${command_path:+$command_path.}${COMP_WORDS[i]}
    done
    case "$command_path" in
        config) COMPREPLY=($(compgen -W "effective layers" -- "$cur")); return ;;
        extension) COMPREPLY=($(compgen -W "disable doctor enable inspect install list purge remove rollback show upgrade validate" -- "$cur")); return ;;
        memory) COMPREPLY=($(compgen -W "observe recall receipt workspace" -- "$cur")); return ;;
        memory.workspace) COMPREPLY=($(compgen -W "bind preview-bind unbind" -- "$cur")); return ;;
        review) COMPREPLY=($(compgen -W "accept repair rollback show" -- "$cur")); return ;;
        exec)
            COMPREPLY=($(compgen -W "--prompt --model --max-turns --sandbox --config --output --idempotency-key --timeout-seconds" -- "$cur"))
            ;;
        run)
            COMPREPLY=($(compgen -W "--resume" -- "$cur"))
            ;;
        completion)
            COMPREPLY=($(compgen -W "bash zsh" -- "$cur"))
            ;;
        daemon)
            COMPREPLY=($(compgen -W "--config --env --socket --container --image --enable-evolution --execd" -- "$cur"))
            ;;
        doctor)
            COMPREPLY=($(compgen -W "--json --config --project-dir" -- "$cur"))
            ;;
    esac
}

complete -F _aletheon_cli_completion aletheon
