#compdef aletheon
# Generated by scripts/generate-command-completions.py from Fabric CommandSpec.
# command-spec-sha256: 579d64d7dc61812ce210d5fe1eb6ddfa24cc4bab6233dbea96c11a16c1a45c04

_aletheon_cli_completion() {
  local -a commands
  local command_path
  commands=(
    'completion:Print a generated shell completion script'
    'config:Inspect effective configuration (merged layers)'
    'daemon:Start daemon (auto-detects systemd/container/foreground)'
    'doctor:Run diagnostics and print a health report'
    'exec:Non-interactive execution'
    'extension:Manage extension packages'
    'memory:Use the governed Memory Gateway through the official user socket'
    'resume:Resume a session or select one from history'
    'review:Inspect or apply a Host-owned change transaction review'
    'run:Run a human-facing governed task'
    'version:Print version'
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi
  command_path="${(j:.:)words[2,CURRENT-1]}"
  case "$command_path" in
    config) _values 'action' effective layers ;;
    extension) _values 'action' disable doctor enable inspect install list purge remove rollback show upgrade validate ;;
    memory) _values 'action' observe recall receipt workspace ;;
    memory.workspace) _values 'action' bind preview-bind unbind ;;
    review) _values 'action' accept repair rollback show ;;
    exec) _arguments '--prompt[task prompt]:' '--model[model route]:' '--max-turns[maximum turns]:' '--sandbox[sandbox preference]:(auto require forbid)' '--config[config file]:_files' '--output[output format]:(text json jsonl)' '--idempotency-key[stable caller key]:' '--timeout-seconds[cancellation deadline]:' ;;
    run) _arguments '--resume[session to resume]:' ;;
    completion) _values 'shell' bash zsh ;;
  esac
}

compdef _aletheon_cli_completion aletheon
