#compdef aletheon
# Generated by scripts/generate-command-completions.py from Fabric CommandSpec.
# command-spec-sha256: 28a1a1dfb44b1deb8ffe0a26287654c0aa041535e06f0bc9a0b5c2016f199253

_aletheon_cli_completion() {
  local -a commands
  local command_path
  commands=(
    'config:Inspect effective configuration (merged layers)'
    'daemon:Start daemon (auto-detects systemd/container/foreground)'
    'doctor:Run diagnostics and print a health report'
    'exec:Non-interactive execution'
    'extension:Manage extension packages'
    'memory:Use the governed Memory Gateway through the official user socket'
    'version:Print version'
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi
  command_path="${(j:.:)words[2,CURRENT-1]}"
  case "$command_path" in
    config) _values 'action' effective layers ;;
    extension) _values 'action' disable doctor enable inspect install list purge remove rollback show upgrade validate ;;
    memory) _values 'action' observe recall receipt workspace ;;
    memory.workspace) _values 'action' bind preview-bind unbind ;;
    exec) _arguments '--prompt[task prompt]:' '--model[model route]:' '--max-turns[maximum turns]:' '--sandbox[sandbox preference]:(auto require forbid)' '--config[config file]:_files' '--output[output format]:(text json)' ;;
  esac
}

compdef _aletheon_cli_completion aletheon
