//! Narrow deterministic audit for completion claims generated by the task
//! contract. It deliberately does not inspect or classify answer prose.

use serde::{Deserialize, Serialize};

use super::cognitive_task::{CognitiveTurnState, Obligation, RequiredAction};
use super::evidence::EvidenceLedger;
use super::progress_auditor::evidence_for_obligation;

#[async_trait::async_trait]
pub trait GroundedOutcomeSink: Send + Sync {
    async fn publish(
        &self,
        outcome: fabric::cognitive_workflow::GroundedCognitiveOutcome,
    ) -> anyhow::Result<()>;
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DeterministicClaim {
    RequiredAgentUsed { runtime: String },
    OperationCompleted { operation: String },
    ValidationPassed { validation_id: String },
    DeliverableProduced { deliverable_id: String },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AuditedClaim {
    pub id: String,
    pub claim: DeterministicClaim,
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ClaimAudit {
    pub supported: Vec<AuditedClaim>,
    pub unsupported: Vec<AuditedClaim>,
}

#[derive(Debug, Default)]
pub struct ClaimEvidenceAuditor;

impl ClaimEvidenceAuditor {
    pub fn audit(&self, state: &CognitiveTurnState, evidence: &EvidenceLedger) -> ClaimAudit {
        let mut audit = ClaimAudit::default();
        for obligation in &state.outstanding {
            let Some((id, claim)) = claim_for(obligation) else {
                continue;
            };
            let record = evidence_for_obligation(obligation, evidence);
            let audited = AuditedClaim {
                id,
                claim,
                evidence_ids: record
                    .map(|record| vec![record.id.0.clone()])
                    .unwrap_or_default(),
            };
            if record.is_some() {
                audit.supported.push(audited);
            } else {
                audit.unsupported.push(audited);
            }
        }
        audit
    }
}

pub fn grounded_completion_outcomes(
    state: &CognitiveTurnState,
    audit: &ClaimAudit,
    completed: bool,
) -> Vec<fabric::cognitive_workflow::GroundedCognitiveOutcome> {
    use fabric::cognitive_workflow::GroundedCognitiveOutcome;
    if completed {
        let mut outcomes = audit
            .supported
            .iter()
            .map(|claim| GroundedCognitiveOutcome::RequirementSatisfied {
                requirement_id: claim.id.clone(),
                evidence: claim.evidence_ids.clone(),
            })
            .collect::<Vec<_>>();
        let evidence = audit
            .supported
            .iter()
            .flat_map(|claim| claim.evidence_ids.iter().cloned())
            .collect();
        outcomes.push(GroundedCognitiveOutcome::TaskCompleted { evidence });
        outcomes
    } else {
        let mut outcomes = state
            .validations
            .iter()
            .filter(|validation| !validation.passed)
            .map(|validation| GroundedCognitiveOutcome::ValidationFailed {
                name: validation.requirement_id.clone(),
                evidence: validation.evidence.0.clone(),
            })
            .collect::<Vec<_>>();
        let mut unsupported = audit
            .unsupported
            .iter()
            .map(|claim| claim.id.clone())
            .collect::<Vec<_>>();
        unsupported.extend(
            state
                .outstanding
                .iter()
                .filter_map(|obligation| match obligation {
                    Obligation::UnresolvedRequirement { description } => {
                        Some(format!("unresolved:{description}"))
                    }
                    _ => None,
                }),
        );
        outcomes.push(GroundedCognitiveOutcome::CompletionRejected {
            missing: unsupported.clone(),
        });
        outcomes.push(GroundedCognitiveOutcome::FalseCompletionPrevented { unsupported });
        outcomes
    }
}

fn claim_for(obligation: &Obligation) -> Option<(String, DeterministicClaim)> {
    match obligation {
        Obligation::RequiredAction(RequiredAction::InvokeAgent { runtime }) => Some((
            format!("required-agent:{}", runtime.0),
            DeterministicClaim::RequiredAgentUsed {
                runtime: runtime.0.clone(),
            },
        )),
        Obligation::RequiredAction(action) => {
            let operation = match action {
                RequiredAction::RunRoleGraph { root_task_id, .. } => {
                    format!("role-graph:{root_task_id}")
                }
                RequiredAction::InvokeAgent { .. } => unreachable!("handled above"),
                RequiredAction::InvokeTool { tool_name } => format!("tool:{tool_name}"),
                RequiredAction::ObserveTerminal { operation_id } => {
                    format!("terminal:{}", operation_id.0)
                }
                RequiredAction::ObserveCommandSession { session_id } => {
                    format!("command-session:{session_id}")
                }
                RequiredAction::ReviewChange {
                    transaction_id,
                    workspace_version,
                } => format!("review:{transaction_id}:{workspace_version}"),
                RequiredAction::ValidateChange {
                    transaction_id,
                    workspace_version,
                } => format!("validation:{transaction_id}:{workspace_version}"),
                RequiredAction::AcceptChange {
                    transaction_id,
                    workspace_version,
                } => format!("acceptance:{transaction_id}:{workspace_version}"),
            };
            Some((
                format!("operation:{operation}"),
                DeterministicClaim::OperationCompleted { operation },
            ))
        }
        Obligation::Validation(validation) => Some((
            format!("validation:{}", validation.id),
            DeterministicClaim::ValidationPassed {
                validation_id: validation.id.clone(),
            },
        )),
        Obligation::Deliverable(deliverable) => Some((
            format!("deliverable:{}", deliverable.id),
            DeterministicClaim::DeliverableProduced {
                deliverable_id: deliverable.id.clone(),
            },
        )),
        Obligation::UnresolvedRequirement { .. } => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::{
        AgentRuntimeId, CognitiveTaskContract, CognitiveTaskKind, EvidenceId, EvidenceLevel,
        EvidenceLocator, EvidenceRecord, EvidenceSource, RequiredAction, TerminalStatus,
    };

    #[test]
    fn contract_claims_require_matching_authoritative_evidence() {
        let runtime = AgentRuntimeId("configured-runtime".into());
        let state = CognitiveTurnState::from_contract(CognitiveTaskContract {
            objective: "use configured runtime".into(),
            task_kind: CognitiveTaskKind::RequiredAgentExecution,
            required_actions: vec![RequiredAction::InvokeAgent {
                runtime: runtime.clone(),
            }],
            deliverables: Vec::new(),
            validation_requirements: Vec::new(),
        });
        let mut ledger = EvidenceLedger::default();
        let missing = ClaimEvidenceAuditor.audit(&state, &ledger);
        assert_eq!(missing.unsupported.len(), 1);
        ledger.record(EvidenceRecord {
            id: EvidenceId("terminal-agent".into()),
            subject: super::super::evidence::EvidenceSubject::AgentInvocation {
                runtime: runtime.clone(),
            },
            source: EvidenceSource::AgentRuntime { runtime },
            level: EvidenceLevel::RuntimeVerified,
            terminal_status: TerminalStatus::Succeeded,
            locator: EvidenceLocator::DurableReceipt {
                receipt_id: "terminal-agent".into(),
            },
            digest: None,
        });
        let supported = ClaimEvidenceAuditor.audit(&state, &ledger);
        assert_eq!(supported.supported[0].evidence_ids, vec!["terminal-agent"]);
        assert!(supported.unsupported.is_empty());
    }

    #[test]
    fn failed_validation_is_published_as_grounded_failure() {
        let mut state = CognitiveTurnState::from_contract(CognitiveTaskContract {
            objective: "validate change".into(),
            task_kind: CognitiveTaskKind::CodeChange,
            required_actions: Vec::new(),
            deliverables: Vec::new(),
            validation_requirements: vec![super::super::cognitive_task::ValidationRequirement {
                id: "focused-test".into(),
                description: "focused test passes".into(),
            }],
        });
        state
            .validations
            .push(super::super::cognitive_task::ValidationRecord {
                requirement_id: "focused-test".into(),
                evidence: EvidenceId("test-output".into()),
                passed: false,
            });
        let audit = ClaimEvidenceAuditor.audit(&state, &EvidenceLedger::default());

        let outcomes = grounded_completion_outcomes(&state, &audit, false);

        assert!(matches!(
            outcomes.first(),
            Some(fabric::cognitive_workflow::GroundedCognitiveOutcome::ValidationFailed {
                name,
                evidence,
            }) if name == "focused-test" && evidence == "test-output"
        ));
    }
}
