#!/usr/bin/env bash
set -euo pipefail

# os-agent setup script
# Usage: ./setup.sh [--dev]

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()   { echo -e "${GREEN}[os-agent]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
err()   { echo -e "${RED}[error]${NC} $*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

DEV_MODE=false
[[ "${1:-}" == "--dev" ]] && DEV_MODE=true

if $DEV_MODE; then
    PROFILE="debug"
    CARGO_FLAGS=""
else
    PROFILE="release"
    CARGO_FLAGS="--release"
fi

# ─── 1. Rust toolchain ───────────────────────────────────────────────
check_rust() {
    if command -v rustc &>/dev/null; then
        log "Rust $(rustc --version) found"
        return 0
    fi
    return 1
}

install_rust() {
    log "Installing Rust via rustup..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"
    log "Rust $(rustc --version) installed"
}

if ! check_rust; then
    install_rust
fi

# ─── 2. System dependencies ──────────────────────────────────────────
install_deps() {
    local pkg_mgr=""
    local pkgs=""

    if command -v pacman &>/dev/null; then
        pkg_mgr="pacman"
        pkgs="bubblewrap sqlite"
    elif command -v apt-get &>/dev/null; then
        pkg_mgr="apt"
        pkgs="bubblewrap libsqlite3-dev"
    elif command -v dnf &>/dev/null; then
        pkg_mgr="dnf"
        pkgs="bubblewrap sqlite-devel"
    else
        warn "Unknown package manager — install bubblewrap and sqlite manually"
        return
    fi

    local missing=()
    for p in $pkgs; do
        case $pkg_mgr in
            pacman) pacman -Qi "$p" &>/dev/null || missing+=("$p") ;;
            apt)    dpkg -s "$p" &>/dev/null    || missing+=("$p") ;;
            dnf)    rpm -q "$p" &>/dev/null      || missing+=("$p") ;;
        esac
    done

    if [[ ${#missing[@]} -eq 0 ]]; then
        log "System dependencies OK"
        return
    fi

    log "Installing missing: ${missing[*]}"
    case $pkg_mgr in
        pacman) sudo pacman -S --noconfirm "${missing[@]}" ;;
        apt)    sudo apt-get install -y "${missing[@]}" ;;
        dnf)    sudo dnf install -y "${missing[@]}" ;;
    esac
}

install_deps

# ─── 3. Build ────────────────────────────────────────────────────────
build() {
    log "Building ($PROFILE)..."
    cargo build $CARGO_FLAGS 2>&1

    log "Running tests..."
    cargo test 2>&1

    log "Build complete: target/$PROFILE/"
}

build

# ─── 4. Config ───────────────────────────────────────────────────────
CONFIG_DIR="$HOME/.os-agent"
CONFIG_FILE="$CONFIG_DIR/config.toml"

setup_config() {
    mkdir -p "$CONFIG_DIR"

    if [[ -f "$CONFIG_FILE" ]]; then
        log "Config exists at $CONFIG_FILE"
        return
    fi

    log "Creating default config..."
    cat > "$CONFIG_FILE" <<'TOML'
# os-agent configuration

[agent]
default_provider = "openai"
default_model = "gpt-4o"
max_iterations = 25
max_tokens = 100000

# ─── Providers ─────────────────────────────────────────────────────────
# Each provider needs: name, base_url, api_key, transport, models
# transport: "auto" (detect from URL) | "openai" | "anthropic"

[[providers]]
name = "openai"
base_url = "https://api.openai.com"
api_key = ""                          # or set OPENAI_API_KEY env var
transport = "openai"
models = ["gpt-4o", "gpt-4o-mini"]

# Example: Anthropic native
# [[providers]]
# name = "anthropic"
# base_url = "https://api.anthropic.com"
# api_key = "sk-ant-..."
# transport = "anthropic"
# models = ["claude-sonnet-4-20250514"]

# Example: DeepSeek
# [[providers]]
# name = "deepseek"
# base_url = "https://api.deepseek.com"
# api_key = "sk-..."
# transport = "openai"
# models = ["deepseek-v4-pro", "deepseek-v4-flash"]

# Example: Xiaomi MiMo (via proxy)
# [[providers]]
# name = "mimo"
# base_url = "https://token-plan-sgp.xiaomimimo.com"
# api_key = "tp-..."
# transport = "auto"                  # auto-detects /anthropic suffix
# models = ["mimo-v2.5-pro"]

# Example: Local Ollama
# [[providers]]
# name = "ollama"
# base_url = "http://localhost:11434"
# api_key = ""
# transport = "openai"
# models = ["qwen3:8b", "llama3:8b"]

# ─── Model Aliases ─────────────────────────────────────────────────────
# Short names for "provider/model" specs
# [model_aliases]
# sonnet = "anthropic/claude-sonnet-4-20250514"
# local = "ollama/qwen3:8b"
TOML
    log "Config written to $CONFIG_FILE"
}

setup_config

# ─── 5. Create convenience wrapper ──────────────────────────────────
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

WRAPPER="$BIN_DIR/os-agent"
TARGET_DIR="target/$PROFILE"

cat > "$WRAPPER" <<WRAPPER_EOF
#!/usr/bin/env bash
# os-agent wrapper — generated by setup.sh
OS_AGENT_ROOT="$SCRIPT_DIR"
OS_AGENT_CONFIG="\$HOME/.os-agent/config.toml"
OS_AGENT_ENV="\$HOME/.os-agent/.env"
OS_AGENT_SOCKET="/tmp/agentd/agent.sock"

export RUST_LOG="\${RUST_LOG:-info}"

usage() {
    cat <<EOF
os-agent — AI agent with sandbox, multi-agent, IPC

Usage:
    os-agent run                 Start daemon + TUI (recommended)
    os-agent daemon              Start daemon (foreground, for debugging)
    os-agent start               Start daemon via systemd
    os-agent stop                Stop daemon
    os-agent restart             Restart daemon
    os-agent status              Show daemon status
    os-agent logs                Follow daemon logs
    os-agent -m <message>        Send a single message
    os-agent                     Interactive mode (TUI if terminal)
    os-agent --help              Show this help

Config:  \$OS_AGENT_CONFIG
Env:     \$OS_AGENT_ENV
Socket:  \$OS_AGENT_SOCKET
EOF
}

case "\${1:-}" in
    daemon)
        # Foreground mode (for debugging)
        # Use 'os-agent start' for systemd-managed background daemon
        mkdir -p "\$(dirname "\$OS_AGENT_SOCKET")"
        exec "\$OS_AGENT_ROOT/$TARGET_DIR/agentd" \\
            --config "\$OS_AGENT_CONFIG" \\
            --env "\$OS_AGENT_ENV" \\
            --socket "\$OS_AGENT_SOCKET" \\
            "\${@:2}"
        ;;
    run)
        # Start daemon in background (logs to file) and launch TUI
        LOG_FILE="\${XDG_STATE_HOME:-\$HOME/.local/state}/os-agent/daemon.log"
        mkdir -p "\$(dirname "\$LOG_FILE")"
        mkdir -p "\$(dirname "\$OS_AGENT_SOCKET")"

        # Kill existing daemon if socket is stale
        if [ -S "\$OS_AGENT_SOCKET" ]; then
            # Check if the process is alive
            if ! lsof "\$OS_AGENT_SOCKET" >/dev/null 2>&1; then
                rm -f "\$OS_AGENT_SOCKET"
            fi
        fi

        # Start daemon in background, redirect logs to file
        if [ ! -S "\$OS_AGENT_SOCKET" ]; then
            "\$OS_AGENT_ROOT/$TARGET_DIR/agentd" \\
                --config "\$OS_AGENT_CONFIG" \\
                --env "\$OS_AGENT_ENV" \\
                --socket "\$OS_AGENT_SOCKET" \\
                >> "\$LOG_FILE" 2>&1 &
            DAEMON_PID=\$!
            echo "Daemon started (pid: \$DAEMON_PID, log: \$LOG_FILE)"
            # Wait for socket to appear
            for i in {1..10}; do
                [ -S "\$OS_AGENT_SOCKET" ] && break
                sleep 0.5
            done
        fi

        # Launch TUI
        exec "\$OS_AGENT_ROOT/$TARGET_DIR/agent-cli" \\
            --socket "\$OS_AGENT_SOCKET" \\
            "\${@:2}"
        ;;
    start)
        systemctl --user start os-agent
        systemctl --user status os-agent --no-pager
        ;;
    stop)
        systemctl --user stop os-agent
        ;;
    restart)
        systemctl --user restart os-agent
        systemctl --user status os-agent --no-pager
        ;;
    status)
        systemctl --user status os-agent --no-pager
        ;;
    logs)
        journalctl --user -u os-agent -f
        ;;
    -m|--message)
        exec "\$OS_AGENT_ROOT/$TARGET_DIR/agent-cli" \\
            --socket "\$OS_AGENT_SOCKET" \\
            -m "\${@:2}"
        ;;
    --help|-h|help)
        usage
        ;;
    *)
        # Interactive mode (no args)
        exec "\$OS_AGENT_ROOT/$TARGET_DIR/agent-cli" \\
            --socket "\$OS_AGENT_SOCKET"
        ;;
esac
WRAPPER_EOF

chmod +x "$WRAPPER"
log "Wrapper installed: $WRAPPER"

# ─── 6. Systemd service ──────────────────────────────────────────────
setup_systemd() {
    local service_dir="$HOME/.config/systemd/user"
    local service_file="$service_dir/os-agent.service"

    mkdir -p "$service_dir"

    cat > "$service_file" <<SERVICE_EOF
[Unit]
Description=OS-Agent daemon
After=network.target

[Service]
Type=simple
ExecStart=$SCRIPT_DIR/$TARGET_DIR/agentd \\
    --config $CONFIG_FILE \\
    --env $CONFIG_DIR/.env \\
    --socket $SOCKET_PATH
Restart=on-failure
RestartSec=5
Environment=RUST_LOG=info

[Install]
WantedBy=default.target
SERVICE_EOF

    log "Systemd service created: $service_file"

    # Reload and enable
    systemctl --user daemon-reload 2>/dev/null || true
    systemctl --user enable os-agent.service 2>/dev/null || true

    echo ""
    echo "  Systemd commands:"
    echo "    systemctl --user start os-agent     # start"
    echo "    systemctl --user stop os-agent      # stop"
    echo "    systemctl --user status os-agent    # status"
    echo "    journalctl --user -u os-agent -f    # logs"
}

SOCKET_PATH="/tmp/agentd/agent.sock"
setup_systemd

# ─── Done ─────────────────────────────────────────────────────────────
echo ""
log "Setup complete!"
echo ""
echo "  Config:    $CONFIG_FILE"
echo "  Binaries:  $SCRIPT_DIR/$TARGET_DIR/"
echo "  Wrapper:   $WRAPPER"
echo ""
echo "  Quick start:"
echo "    export OPENAI_API_KEY='sk-...'"
echo "    os-agent daemon          # start daemon"
echo "    os-agent chat 'hello'    # chat"
echo ""
echo "  Or without wrapper:"
echo "    ./target/${PROFILE}/agentd"
echo "    ./target/${PROFILE}/agent-cli chat 'hello'"
echo ""
