//! SelfField trait — like Linux kernel's LSM / SELinux.
//!
//! SelfField is the policy engine. It reviews intents, enforces boundaries,
//! resolves conflicts, and maintains identity continuity.
//! It is not a module — it's a field. But it has a trait interface.

use anyhow::Result;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::context::Context;
use crate::subsystem::Subsystem;

/// Verdict from SelfField review — like SELinux allow/deny.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Verdict {
    /// Allow the action without modification.
    Allow,
    /// Allow with modification (SelfField rewrote the intent).
    AllowWithModification { modification: serde_json::Value },
    /// Deny the action.
    Deny { reason: String },
    /// Require user confirmation before proceeding.
    RequireConfirmation {
        reason: String,
        risk_level: RiskLevel,
    },
    /// Must run in sandbox first.
    SandboxFirst { reason: String },
    /// Delay execution until condition is met.
    Delay { reason: String, until: String },
}

/// Risk level for actions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RiskLevel {
    None = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4,
}

/// An intent — something that wants to happen.
///
/// Could be a user request, a BrainCore plan, or a MetaRuntime mutation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Intent {
    /// What wants to happen.
    pub action: String,
    /// Parameters.
    pub parameters: serde_json::Value,
    /// Source of the intent (user, brain, meta, etc.).
    pub source: IntentSource,
    /// Human-readable description.
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum IntentSource {
    User,
    Brain,
    Body,
    Memory,
    Meta,
    External,
}

/// Identity — current self model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Identity {
    pub name: String,
    pub description: String,
    pub version: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub last_mutation: Option<chrono::DateTime<chrono::Utc>>,
}

/// A care — something the agent values.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Care {
    pub topic: String,
    pub weight: f64, // 0.0 to 1.0
    pub description: String,
}

/// A conflict between multiple opinions.
#[derive(Debug, Clone)]
pub struct Conflict {
    pub source_a: ConflictSource,
    pub source_b: ConflictSource,
    pub context: Context,
}

/// Source of a conflicting opinion.
#[derive(Debug, Clone)]
pub enum ConflictSource {
    User { intent: String },
    Brain { proposal: String, confidence: f64 },
    Body { objection: String, risk: RiskLevel },
    Memory { evidence: String },
    Self_ { concern: String },
}

/// Resolution of a conflict.
#[derive(Debug, Clone)]
pub enum Resolution {
    AcceptA { reason: String },
    AcceptB { reason: String },
    Compromise { action: String, reason: String },
    EscalateToUser { question: String },
    SandboxExperiment { plan: String },
}

/// A mutation intent — how the agent wants to change itself.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MutationIntent {
    pub target: String, // What to change (e.g., "boundary_rules", "care_priorities")
    pub change: serde_json::Value, // The proposed change
    pub reason: String, // Why
    pub reversible: bool, // Can this be undone?
}

/// Self-awareness information format.
///
/// Generated by BrainCore during reasoning, this carries the agent's
/// awareness of its own mental state. Corresponds to Spinoza's idea ideae:
/// the idea of an idea is inherent in every idea.
///
/// This is not a separate module — it's an information format that
/// travels with every reasoning action.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SelfAwareness {
    /// Minimal core: the irreducible reflexive structure
    pub core: AwarenessCore,
    /// Extension layers: grow based on experience
    pub extensions: Vec<AwarenessExtension>,
}

impl SelfAwareness {
    /// Create a minimal awareness with just the core.
    /// This is the seed — the smallest possible self-awareness.
    pub fn minimal(action: impl Into<String>) -> Self {
        Self {
            core: AwarenessCore {
                action: action.into(),
                aware: true, // Always true — awareness is present by definition
            },
            extensions: Vec::new(),
        }
    }

    /// Create awareness with extensions.
    pub fn with_extensions(action: impl Into<String>, extensions: Vec<AwarenessExtension>) -> Self {
        Self {
            core: AwarenessCore {
                action: action.into(),
                aware: true,
            },
            extensions,
        }
    }

    /// Serialize to JSON bytes for storage.
    pub fn to_json_bytes(&self) -> Vec<u8> {
        serde_json::to_vec(self).unwrap_or_default()
    }

    /// Deserialize from JSON bytes.
    pub fn from_json_bytes(bytes: &[u8]) -> Option<Self> {
        serde_json::from_slice(bytes).ok()
    }

    /// Count extensions by type (for growth analysis).
    pub fn extension_counts(&self) -> AwarenessExtensionCounts {
        let mut counts = AwarenessExtensionCounts::default();
        for ext in &self.extensions {
            match ext {
                AwarenessExtension::Intent { .. } => counts.intent += 1,
                AwarenessExtension::SelfState { .. } => counts.self_state += 1,
                AwarenessExtension::Significance { .. } => counts.significance += 1,
                AwarenessExtension::Reflexive { .. } => counts.reflexive += 1,
            }
        }
        counts
    }
}

/// Minimal reflexive core.
///
/// Corresponds to Spinoza's idea ideae: awareness is inherent in every
/// mental act. The `aware` field is always true — its presence IS the awareness.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AwarenessCore {
    /// What I am doing right now
    pub action: String,
    /// I know I am doing this (always true)
    /// Presence of SelfAwareness = awareness is present
    pub aware: bool,
}

/// Extension layers for self-awareness.
///
/// Initial four variants. Grows based on experience — BrainCore
/// analyzes its awareness history and adds extensions that are
/// grounded in observed patterns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AwarenessExtension {
    /// Why I am doing this (final cause)
    Intent { reason: String },
    /// My current state (present self-perception)
    SelfState { state: SelfState },
    /// What this means to me (relation to identity)
    Significance { meaning: String },
    /// Awareness of awareness (recursive reflexive)
    /// Depth is bounded by experience, not by code
    Reflexive { meta: Box<SelfAwareness> },
}

/// Self-state descriptor — how the agent feels in this moment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SelfState {
    /// Engaged and focused
    Focused,
    /// Uncertain, seeking clarity
    Confused,
    /// High confidence in current reasoning
    Confident,
    /// Between options, weighing
    Hesitant,
    /// Exploring, seeking new information
    Curious,
    /// Other state (free-form description)
    Other(String),
}

/// Counts of awareness extensions by type — used for growth analysis.
#[derive(Debug, Clone, Default)]
pub struct AwarenessExtensionCounts {
    pub intent: usize,
    pub self_state: usize,
    pub significance: usize,
    pub reflexive: usize,
}

/// Growth suggestion for awareness extensions.
///
/// Produced by AwarenessGrowthAnalyzer based on historical patterns.
/// Consumed by BrainCore to enrich future awareness generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AwarenessGrowthSuggestion {
    /// Which extension type is suggested
    pub extension_type: String,
    /// Why this extension is suggested (pattern-based reason)
    pub reason: String,
    /// Confidence in this suggestion (0.0 to 1.0)
    pub confidence: f64,
}

/// What to do after handling a SelfField verdict.
#[derive(Debug, Clone)]
pub enum VerdictAction {
    /// Proceed with execution (possibly with modified intent).
    Proceed {
        modified_intent: Option<Intent>,
    },
    /// Short-circuit with a response (denial, confirmation-rejected, delay).
    ShortCircuit {
        response: String,
    },
    /// Run in sandbox first, then proceed if test passes.
    SandboxThenProceed {
        reason: String,
    },
}

/// Handles a SelfField verdict before execution.
///
/// Implementations decide how to act on each verdict type. The default
/// implementation maps Allow -> Proceed, Deny -> ShortCircuit, etc.
pub trait VerdictHandler: Send + Sync {
    fn handle(&self, verdict: &Verdict, intent: &Intent, ctx: &Context) -> VerdictAction;
}

/// SelfField trait — the LSM policy engine.
///
/// SelfField reviews intents, enforces boundaries, resolves conflicts,
/// and maintains identity continuity. It is the "should I?" layer.
#[async_trait]
pub trait SelfFieldOps: Subsystem {
    /// Review an intent. Returns a verdict.
    ///
    /// This is the core operation — like an LSM hook. Every significant
    /// action passes through here before execution.
    async fn review(&self, intent: &Intent, ctx: &Context) -> Result<Verdict>;

    /// Get current identity.
    async fn identity(&self) -> Result<Identity>;

    /// Get current cares.
    async fn cares(&self) -> Result<Vec<Care>>;

    /// Record a narrative — why a decision was made.
    ///
    /// This is how the agent explains itself. Not just logging —
    /// it's the continuity of self-narrative.
    async fn narrate(&self, event: &str, reason: &str) -> Result<()>;

    /// Resolve an internal conflict.
    async fn resolve_conflict(&self, conflict: &Conflict) -> Result<Resolution>;

    /// Review a mutation intent — should the agent change itself?
    async fn review_mutation(&self, mutation: &MutationIntent) -> Result<Verdict>;
}
