#!/usr/bin/env python3
"""Generate installed shell completion command trees from Fabric CommandSpec data."""

from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "crates/fabric/src/contract/command-specs.tsv"
BASH = ROOT / "scripts/completions/aletheon.bash"
ZSH = ROOT / "scripts/completions/aletheon.zsh"


def rows() -> list[dict[str, str]]:
    with SPEC.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader((line for line in handle if not line.startswith("# key")), delimiter="\t", fieldnames=[
            "key", "surface", "parent", "name", "aliases", "summary", "category",
            "usage", "execution", "availability", "visibility", "intent",
        ]))


def cli_children(entries: list[dict[str, str]], parent: str = "-") -> list[dict[str, str]]:
    return sorted(
        (
            row
            for row in entries
            if row["surface"] == "cli"
            and row["parent"] == parent
            and row["visibility"] == "public"
        ),
        key=lambda row: row["name"],
    )


def digest() -> str:
    return hashlib.sha256(SPEC.read_bytes()).hexdigest()


def cli_parent_paths(entries: list[dict[str, str]]) -> list[str]:
    return sorted(
        {
            row["parent"]
            for row in entries
            if row["surface"] == "cli"
            and row["parent"] != "-"
            and row["visibility"] == "public"
        }
    )


def bash_text(entries: list[dict[str, str]]) -> str:
    roots = " ".join(row["name"] for row in cli_children(entries))
    nested_cases = "\n".join(
        f'        {parent}) COMPREPLY=($(compgen -W "'
        + " ".join(row["name"] for row in cli_children(entries, parent))
        + '" -- "$cur")); return ;;'
        for parent in cli_parent_paths(entries)
    )
    return f'''# Generated by scripts/generate-command-completions.py from Fabric CommandSpec.
# command-spec-sha256: {digest()}

_aletheon_cli_completion() {{
    local cur prev command_path i
    COMPREPLY=()
    cur=${{COMP_WORDS[COMP_CWORD]}}
    prev=${{COMP_WORDS[COMP_CWORD-1]:-}}

    case "$prev" in
        -C|--working-dir|--add-dir|--config|-c|--env|--project-dir|-d)
            COMPREPLY=($(compgen -d -- "$cur")); return ;;
        path)
            COMPREPLY=($(compgen -f -- "$cur")); return ;;
        -P|--permission-mode)
            COMPREPLY=($(compgen -W "safe dev full" -- "$cur")); return ;;
        --output)
            COMPREPLY=($(compgen -W "text json jsonl" -- "$cur")); return ;;
        --sandbox)
            COMPREPLY=($(compgen -W "auto require forbid" -- "$cur")); return ;;
    esac

    if ((COMP_CWORD == 1)); then
        COMPREPLY=($(compgen -W "{roots} --help --version --full --permission-mode --message --socket --task-kind -C --add-dir" -- "$cur"))
        return
    fi

    command_path=""
    for ((i=1; i<COMP_CWORD; i++)); do
        command_path=${{command_path:+$command_path.}}${{COMP_WORDS[i]}}
    done
    case "$command_path" in
{nested_cases}
        exec)
            COMPREPLY=($(compgen -W "--prompt --model --max-turns --sandbox --config --output --idempotency-key --timeout-seconds" -- "$cur"))
            ;;
        run)
            COMPREPLY=($(compgen -W "--resume" -- "$cur"))
            ;;
        completion)
            COMPREPLY=($(compgen -W "bash zsh" -- "$cur"))
            ;;
        daemon)
            COMPREPLY=($(compgen -W "--config --env --socket --container --image --enable-evolution --execd" -- "$cur"))
            ;;
        doctor)
            COMPREPLY=($(compgen -W "--json --config --project-dir" -- "$cur"))
            ;;
    esac
}}

complete -F _aletheon_cli_completion aletheon
'''


def zsh_text(entries: list[dict[str, str]]) -> str:
    command_lines = "\n".join(
        f"    '{row['name']}:{row['summary'].replace(chr(39), chr(39) + '\\\\' + chr(39))}'"
        for row in cli_children(entries)
    )
    nested_cases = "\n".join(
        f"    {parent}) _values 'action' "
        + " ".join(row["name"] for row in cli_children(entries, parent))
        + " ;;"
        for parent in cli_parent_paths(entries)
    )
    return f'''#compdef aletheon
# Generated by scripts/generate-command-completions.py from Fabric CommandSpec.
# command-spec-sha256: {digest()}

_aletheon_cli_completion() {{
  local -a commands
  local command_path
  commands=(
{command_lines}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi
  command_path="${{(j:.:)words[2,CURRENT-1]}}"
  case "$command_path" in
{nested_cases}
    exec) _arguments '--prompt[task prompt]:' '--model[model route]:' '--max-turns[maximum turns]:' '--sandbox[sandbox preference]:(auto require forbid)' '--config[config file]:_files' '--output[output format]:(text json jsonl)' '--idempotency-key[stable caller key]:' '--timeout-seconds[cancellation deadline]:' ;;
    run) _arguments '--resume[session to resume]:' ;;
    completion) _values 'shell' bash zsh ;;
  esac
}}

compdef _aletheon_cli_completion aletheon
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    entries = rows()
    generated = {BASH: bash_text(entries), ZSH: zsh_text(entries)}
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, content in generated.items() if path.read_text(encoding="utf-8") != content]
        if stale:
            print("command completion assets are stale: " + ", ".join(stale), file=sys.stderr)
            return 1
        print("command completion assets: pass")
        return 0
    for path, content in generated.items():
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
